[2024-12-18T15:44:50.560+0000] {processor.py:186} INFO - Started process (PID=3672) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:44:50.561+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:44:50.563+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:44:50.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:44:50.567+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:44:50.567+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:44:50.568+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:44:50.568+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:44:50.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:44:50.580+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T15:45:59.569+0000] {processor.py:186} INFO - Started process (PID=3775) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:45:59.570+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:45:59.572+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:45:59.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:45:59.576+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:45:59.575+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:45:59.576+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:45:59.576+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:45:59.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:45:59.597+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-12-18T15:46:55.477+0000] {processor.py:186} INFO - Started process (PID=4242) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:46:55.478+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:46:55.480+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:46:55.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:46:55.484+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:46:55.483+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:46:55.485+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:46:55.484+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:46:55.485+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:46:55.497+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T15:47:53.352+0000] {processor.py:186} INFO - Started process (PID=4300) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:47:53.354+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:47:53.356+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:47:53.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:47:53.360+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:47:53.359+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:47:53.360+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:47:53.360+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:47:53.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:47:53.373+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T15:48:48.262+0000] {processor.py:186} INFO - Started process (PID=4356) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:48:48.264+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:48:48.266+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:48:48.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:48:48.269+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:48:48.269+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:48:48.270+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:48:48.270+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:48:48.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:48:48.282+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T15:49:52.705+0000] {processor.py:186} INFO - Started process (PID=4417) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:49:52.707+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:49:52.709+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:49:52.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:49:52.713+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:49:52.712+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:49:52.713+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:49:52.713+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:49:52.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:49:52.725+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T15:50:50.484+0000] {processor.py:186} INFO - Started process (PID=4487) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:50:50.486+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:50:50.488+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:50:50.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:50:50.492+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:50:50.491+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:50:50.492+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:50:50.492+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:50:50.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:50:50.504+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T15:51:45.073+0000] {processor.py:186} INFO - Started process (PID=4546) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:51:45.075+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:51:45.079+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:51:45.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:51:45.087+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:51:45.085+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:51:45.087+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:51:45.087+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:51:45.089+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:51:45.102+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-12-18T15:52:39.585+0000] {processor.py:186} INFO - Started process (PID=4603) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:52:39.587+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:52:39.589+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:52:39.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:52:39.593+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:52:39.592+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:52:39.593+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:52:39.593+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:52:39.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:52:39.606+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T15:53:34.626+0000] {processor.py:186} INFO - Started process (PID=4659) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:53:34.628+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:53:34.630+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:53:34.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:53:34.634+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:53:34.633+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:53:34.634+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:53:34.634+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:53:34.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:53:34.647+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T15:55:00.200+0000] {processor.py:186} INFO - Started process (PID=4773) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:55:00.202+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:55:00.204+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:55:00.203+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:55:00.208+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:55:00.207+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:55:00.208+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:55:00.208+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:55:00.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:55:00.220+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-12-18T15:55:57.161+0000] {processor.py:186} INFO - Started process (PID=4836) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:55:57.163+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:55:57.165+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:55:57.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:55:57.169+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:55:57.168+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:55:57.169+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:55:57.169+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:55:57.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:55:57.182+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-12-18T15:57:27.721+0000] {processor.py:186} INFO - Started process (PID=4923) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:57:27.723+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:57:27.725+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:57:27.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:57:27.728+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:57:27.728+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:57:27.729+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:57:27.729+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:57:27.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:57:27.741+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T15:58:24.566+0000] {processor.py:186} INFO - Started process (PID=4981) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:58:24.567+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:58:24.569+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:58:24.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:58:24.573+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:58:24.572+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:58:24.573+0000] {logging_mixin.py:190} INFO - [2024-12-18T15:58:24.573+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:58:24.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:58:24.586+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T16:00:26.534+0000] {processor.py:186} INFO - Started process (PID=5107) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:00:26.535+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T16:00:26.537+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:00:26.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:00:26.541+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:00:26.540+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T16:00:26.542+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:00:26.541+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T16:00:26.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:00:26.554+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T16:01:23.383+0000] {processor.py:186} INFO - Started process (PID=5166) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:01:23.384+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T16:01:23.387+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:01:23.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:01:23.390+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:01:23.390+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T16:01:23.391+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:01:23.391+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T16:01:23.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:01:23.403+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T16:02:19.926+0000] {processor.py:186} INFO - Started process (PID=5225) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:02:19.927+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T16:02:19.929+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:02:19.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:02:19.933+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:02:19.932+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T16:02:19.934+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:02:19.933+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T16:02:19.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:02:19.945+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T16:03:14.633+0000] {processor.py:186} INFO - Started process (PID=5280) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:03:14.634+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T16:03:14.637+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:03:14.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:03:14.641+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:03:14.640+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T16:03:14.641+0000] {logging_mixin.py:190} INFO - [2024-12-18T16:03:14.641+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T16:03:14.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:03:14.654+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:29:54.588+0000] {processor.py:186} INFO - Started process (PID=2760) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:29:54.590+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:29:54.593+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:29:54.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:29:54.597+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:29:54.597+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:29:54.598+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:29:54.598+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:29:54.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:29:54.611+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-12-18T20:30:52.707+0000] {processor.py:186} INFO - Started process (PID=2943) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:30:52.709+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:30:52.711+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:30:52.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:30:52.715+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:30:52.715+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:30:52.716+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:30:52.716+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:30:52.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:30:52.728+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:31:48.120+0000] {processor.py:186} INFO - Started process (PID=3171) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:31:48.122+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:31:48.124+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:31:48.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:31:48.128+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:31:48.127+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:31:48.129+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:31:48.129+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:31:48.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:31:48.141+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:32:45.415+0000] {processor.py:186} INFO - Started process (PID=3414) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:32:45.417+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:32:45.419+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:32:45.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:32:45.423+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:32:45.422+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:32:45.423+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:32:45.423+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:32:45.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:32:45.435+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T20:33:38.799+0000] {processor.py:186} INFO - Started process (PID=3531) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:33:38.801+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:33:38.803+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:33:38.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:33:38.807+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:33:38.806+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:33:38.807+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:33:38.807+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:33:38.808+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:33:38.819+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T20:34:48.506+0000] {processor.py:186} INFO - Started process (PID=3717) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:34:48.508+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:34:48.510+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:34:48.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:34:48.514+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:34:48.514+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:34:48.515+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:34:48.515+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:34:48.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:34:48.528+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-12-18T20:35:46.838+0000] {processor.py:186} INFO - Started process (PID=3842) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:35:46.839+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:35:46.842+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:35:46.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:35:46.846+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:35:46.845+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:35:46.846+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:35:46.846+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:35:46.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:35:46.862+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-12-18T20:36:44.248+0000] {processor.py:186} INFO - Started process (PID=3960) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:36:44.250+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:36:44.253+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:36:44.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:36:44.257+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:36:44.256+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:36:44.257+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:36:44.257+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:36:44.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:36:44.269+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-12-18T20:37:40.262+0000] {processor.py:186} INFO - Started process (PID=4079) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:37:40.264+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:37:40.266+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:37:40.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:37:40.270+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:37:40.270+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:37:40.271+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:37:40.271+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:37:40.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:37:40.283+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:38:34.781+0000] {processor.py:186} INFO - Started process (PID=4194) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:38:34.783+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:38:34.786+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:38:34.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:38:34.790+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:38:34.789+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:38:34.790+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:38:34.790+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:38:34.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:38:34.802+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:39:30.384+0000] {processor.py:186} INFO - Started process (PID=4373) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:39:30.385+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:39:30.388+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:39:30.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:39:30.392+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:39:30.391+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:39:30.392+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:39:30.392+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:39:30.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:39:30.405+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-12-18T20:40:28.075+0000] {processor.py:186} INFO - Started process (PID=4509) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:40:28.077+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:40:28.079+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:40:28.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:40:28.083+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:40:28.083+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:40:28.084+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:40:28.084+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:40:28.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:40:28.096+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-12-18T20:41:22.369+0000] {processor.py:186} INFO - Started process (PID=4628) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:41:22.371+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:41:22.373+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:41:22.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:41:22.377+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:41:22.376+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:41:22.378+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:41:22.378+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:41:22.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:41:22.390+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:42:17.084+0000] {processor.py:186} INFO - Started process (PID=4710) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:42:17.086+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:42:17.088+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:42:17.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:42:17.092+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:42:17.091+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:42:17.092+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:42:17.092+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:42:17.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:42:17.105+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:43:12.068+0000] {processor.py:186} INFO - Started process (PID=4801) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:43:12.069+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:43:12.072+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:43:12.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:43:12.076+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:43:12.075+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:43:12.076+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:43:12.076+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:43:12.077+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:43:12.088+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T20:44:05.819+0000] {processor.py:186} INFO - Started process (PID=4916) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:44:05.820+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:44:05.823+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:44:05.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:44:05.826+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:44:05.826+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:44:05.827+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:44:05.827+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:44:05.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:44:05.839+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:44:59.555+0000] {processor.py:186} INFO - Started process (PID=5094) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:44:59.556+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:44:59.559+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:44:59.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:44:59.563+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:44:59.562+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:44:59.563+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:44:59.563+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:44:59.564+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:44:59.576+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-12-18T20:45:54.017+0000] {processor.py:186} INFO - Started process (PID=5216) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:45:54.018+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:45:54.020+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:45:54.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:45:54.024+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:45:54.024+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:45:54.025+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:45:54.025+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:45:54.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:45:54.037+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-18T20:47:32.781+0000] {processor.py:186} INFO - Started process (PID=5841) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:47:32.783+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:47:32.786+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:47:32.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:47:32.790+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:47:32.789+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:47:32.790+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:47:32.790+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:47:32.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:47:32.803+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-12-18T20:48:32.298+0000] {processor.py:186} INFO - Started process (PID=6144) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:48:32.299+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:48:32.302+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:48:32.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:48:32.305+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:48:32.305+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:48:32.306+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:48:32.306+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:48:32.306+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:48:32.318+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:49:28.174+0000] {processor.py:186} INFO - Started process (PID=6442) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:49:28.175+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:49:28.177+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:49:28.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:49:28.181+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:49:28.181+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:49:28.182+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:49:28.182+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:49:28.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:49:28.195+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-12-18T20:50:26.324+0000] {processor.py:186} INFO - Started process (PID=6804) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:50:26.326+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:50:26.328+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:50:26.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:50:26.332+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:50:26.332+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:50:26.333+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:50:26.333+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:50:26.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:50:26.345+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-12-18T20:51:21.654+0000] {processor.py:186} INFO - Started process (PID=6982) to work on /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:51:21.656+0000] {processor.py:914} INFO - Processing file /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T20:51:21.658+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:51:21.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:51:21.663+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:51:21.662+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T20:51:21.663+0000] {logging_mixin.py:190} INFO - [2024-12-18T20:51:21.663+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T20:51:21.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T20:51:21.676+0000] {processor.py:208} INFO - Processing /home/ubuntu/demo8/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
